### ISSUE TITLE
Issues with datamining the Cookies' sprites.

### ISSUE THREAD

**Issue by RiffyDiffy** [syrupyy/cookiecomiccreator#4]
Hi, again! This is RiffyDiffy, one of the admins from the Cookie Run: Kingdom Wiki.

I know this is not the VG-Resource, nor is it related to the Cookie Comic Creator project, but I figured I could need some help.

So, apparently, starting from the Save The Future update, only the new Cookies' spritesheets are added, not the old ones.

To show you proof, here is a screenshot of the issue.
![Bluestacks_ZueyXhuEO9](https://user-images.githubusercontent.com/81842790/149666962-2a3f18ac-989c-44c5-8b23-28c07764b7f3.png)
The screenshot shows no spritesheets for GingerBright, Strawberry Cookie, Skater Cookie, etc... Just only the newly-released spritesheets.

Yes, I turned off Segmented Downloads, but the issue still persists.
Is there any ways to fix this?

Thanks for reading this!
-RiffyDiffy

**Comment by winterbreezesrule** [comment]
I believe the reason this happens is because CROB has moved from downloading the old sprites to including them in the APK itself, in one of the bundled ones (if I remember correctly, the Android store downloads an XAPK that includes three smaller APKs? Or maybe an APK and two OBBs? Something like that.)

That's why the download size from the app store has inflated so drastically. It's...a little convoluted, honestly.

**Comment by RiffyDiffy** [comment]
@winterbreezesrule 
Hey, I remember you!

I'll check if it contains the old sprites, then come back with the news.

**Comment by syrupyy** [comment]
correct! that is why the apk's files are combined with those files in this repo

**Comment by RiffyDiffy** [comment]
Ermm... I hit a roadblock.

How do you get the three .APK's you guys mentioned, again?

**Comment by winterbreezesrule** [comment]
![image](https://user-images.githubusercontent.com/48916147/149668228-fade0059-a005-4396-8ee1-8f86fcff3cef.png)

This is the path you should follow (apologies for the mess my Xplorer is at the moment, haha).

**Comment by RiffyDiffy** [comment]
Not sure... the old sprites aren't there.

**Comment by winterbreezesrule** [comment]
They should be in the split.googleplay.assetpack.apk\assets\release ?

**Comment by RiffyDiffy** [comment]
Ooooohh...
Thank you so much!
